/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.bear.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class DependencyPlugin implements Plugin<Project> {
    def version = 1

    void apply(Project project) {

        project.afterEvaluate {
            println("========================do afterEvaluate task version<$version>======================")
            Properties properties = new Properties()
            properties.load(project.rootProject.file('dependencies.properties').newDataInputStream())
            def imageLib = properties.getProperty("imageLibs")
            def dependenceList = imageLib.split(",")
            dependenceList.each {
                println("implementation: $it")
                project.dependencies.add("implementation", it)
            }
        }
    }
}
